/*
 * Yol nişanları bazası — AVTOMATİK YARADILIB, əl ilə redaktə etməyin.
 * Yenidən qurmaq üçün: node tools/build-nisanlar.js
 *
 * Mənbə: Azərbaycan Respublikası Baş Dövlət Yol Polisi İdarəsi — dyp.gov.az
 * Şəkillər: /assets/nisanlar/<kat>/<img>
 * Cəmi 305 nişan, 10 kateqoriya.
 */
window.NISAN_KATEQORIYALARI = [
  { id: "xeberdarliq", ad: "Xəbərdarlıq nişanları", qisa: "Xəbərdarlıq", test: true },
  { id: "ustunluk", ad: "Üstünlük nişanları", qisa: "Üstünlük", test: true },
  { id: "qadagan", ad: "Qadağan nişanları", qisa: "Qadağan", test: true },
  { id: "mecburi", ad: "Məcburi hərəkət istiqaməti nişanları", qisa: "Məcburi hərəkət", test: true },
  { id: "melumatverici", ad: "Məlumatverici-göstərici nişanlar", qisa: "Məlumatverici", test: true },
  { id: "servis", ad: "Servis nişanları", qisa: "Servis", test: true },
  { id: "elave-melumat", ad: "Əlavə məlumat nişanları (lövhəciklər)", qisa: "Əlavə məlumat", test: true },
  { id: "taninma", ad: "Nəqliyyat vasitələrinin tanınma nişanları", qisa: "Tanınma nişanları", test: true },
  { id: "yol-isleri", ad: "Yol işlərində istifadə olunan işarələr", qisa: "Yol işləri", test: true },
  { id: "nisanlanma", ad: "Yolların nişanlanması", qisa: "Nişanlanma", test: false },
];

window.NISANLAR = [
  { n: "1.1", ad: "Şlaqbaumlu dəmir yol keçidi", kat: "xeberdarliq", img: "1-1.gif" },
  { n: "1.2", ad: "Şlaqbaumsuz dəmir yol keçidi", kat: "xeberdarliq", img: "1-2.gif" },
  { n: "1.3.1", ad: "Birxətli dəmir yolu", kat: "xeberdarliq", img: "1-3-1.gif" },
  { n: "1.3.2", ad: "Çoxxətli dəmir yolu", kat: "xeberdarliq", img: "1-3-2.gif" },
  { n: "1.4.1", ad: "Dəmir yol keçidinə yaxınlaşma", kat: "xeberdarliq", img: "1-4-1.gif" },
  { n: "1.4.2", ad: "Dəmir yol keçidinə yaxınlaşma", kat: "xeberdarliq", img: "1-4-2.gif" },
  { n: "1.4.3", ad: "Dəmir yol keçidinə yaxınlaşma", kat: "xeberdarliq", img: "1-4-3.gif" },
  { n: "1.4.4", ad: "Dəmir yol keçidinə yaxınlaşma", kat: "xeberdarliq", img: "1-4-4.gif" },
  { n: "1.4.5", ad: "Dəmir yol keçidinə yaxınlaşma", kat: "xeberdarliq", img: "1-4-5.gif" },
  { n: "1.4.6", ad: "Dəmir yol keçidinə yaxınlaşma", kat: "xeberdarliq", img: "1-4-6.gif" },
  { n: "1.5", ad: "Tramvay xətti ilə kəsişmə", kat: "xeberdarliq", img: "1-5.gif" },
  { n: "1.6", ad: "Eyni əhəmiyyətli yolların kəsişməsi", kat: "xeberdarliq", img: "1-6.gif" },
  { n: "1.7", ad: "Dairəvi hərəkətlə kəsişmə", kat: "xeberdarliq", img: "1-7.gif" },
  { n: "1.8", ad: "Svetoforla nizamlama", kat: "xeberdarliq", img: "1-8.gif" },
  { n: "1.9", ad: "Ayrılan körpü", kat: "xeberdarliq", img: "1-9.gif" },
  { n: "1.10", ad: "Sahilboyuna çıxış", kat: "xeberdarliq", img: "1-10.gif" },
  { n: "1.11.1", ad: "Təhlükəli döngə", kat: "xeberdarliq", img: "1-11-1.gif" },
  { n: "1.11.2", ad: "Təhlükəli döngə", kat: "xeberdarliq", img: "1-11-2.gif" },
  { n: "1.12.1", ad: "Təhlükəli döngələr", kat: "xeberdarliq", img: "1-12-1.gif" },
  { n: "1.12.2", ad: "Təhlükəli döngələr", kat: "xeberdarliq", img: "1-12-2.gif" },
  { n: "1.13", ad: "Sərt eniş", kat: "xeberdarliq", img: "1-13.gif" },
  { n: "1.14", ad: "Sərt yoxuş", kat: "xeberdarliq", img: "1-14.gif" },
  { n: "1.15", ad: "Sürüşkən yol", kat: "xeberdarliq", img: "1-15.gif" },
  { n: "1.16", ad: "Nahamar yol", kat: "xeberdarliq", img: "1-16.gif" },
  { n: "1.17", ad: "Çınqıl sıçrayışı", kat: "xeberdarliq", img: "1-17.gif" },
  { n: "1.18.1", ad: "Yolun daralması", kat: "xeberdarliq", img: "1-18-1.gif" },
  { n: "1.18.2", ad: "Yolun daralması", kat: "xeberdarliq", img: "1-18-2.gif" },
  { n: "1.18.3", ad: "Yolun daralması", kat: "xeberdarliq", img: "1-18-3.gif" },
  { n: "1.19", ad: "İkitərəfli hərəkət", kat: "xeberdarliq", img: "1-19.gif" },
  { n: "1.20", ad: "Piyada keçidi", kat: "xeberdarliq", img: "1-20.gif" },
  { n: "1.21", ad: "Uşaqlar", kat: "xeberdarliq", img: "1-21.gif" },
  { n: "1.22", ad: "Velosiped zolağı ilə kəsişmə", kat: "xeberdarliq", img: "1-22.gif" },
  { n: "1.23", ad: "Yol işləri", kat: "xeberdarliq", img: "1-23.gif" },
  { n: "1.24", ad: "Mal-qara keçidi", kat: "xeberdarliq", img: "1-24.gif" },
  { n: "1.25", ad: "Vəhşi heyvanlar", kat: "xeberdarliq", img: "1-25.gif" },
  { n: "1.26", ad: "Daş uçqunu", kat: "xeberdarliq", img: "1-26.gif" },
  { n: "1.27", ad: "Yandan əsən külək", kat: "xeberdarliq", img: "1-27.gif" },
  { n: "1.28", ad: "Alçaqdan uçan təyyarələr", kat: "xeberdarliq", img: "1-28.gif" },
  { n: "1.29", ad: "Tunel", kat: "xeberdarliq", img: "1-29.gif" },
  { n: "1.30", ad: "Digər təhlükələr", kat: "xeberdarliq", img: "1-30.gif" },
  { n: "1.31.1", ad: "Döngənin istiqaməti", kat: "xeberdarliq", img: "1-31-1.gif" },
  { n: "1.31.2", ad: "Döngənin istiqaməti", kat: "xeberdarliq", img: "1-31-2.gif" },
  { n: "1.31.3", ad: "Döngənin istiqaməti", kat: "xeberdarliq", img: "1-31-3.gif" },
  { n: "2.1", ad: "Baş yol", kat: "ustunluk", img: "2-1.gif" },
  { n: "2.2", ad: "Baş yolun sonu", kat: "ustunluk", img: "2-2.gif" },
  { n: "2.3.1", ad: "İkinci dərəcəli yolla kəsişmə", kat: "ustunluk", img: "2-3-1.gif" },
  { n: "2.3.2", ad: "İkinci dərəcəli yolun bitişməsi", kat: "ustunluk", img: "2-3-2.gif" },
  { n: "2.3.3", ad: "İkinci dərəcəli yolun bitişməsi", kat: "ustunluk", img: "2-3-3.gif" },
  { n: "2.4", ad: "Yol verin", kat: "ustunluk", img: "2-4.gif" },
  { n: "2.5", ad: "Dayanmadan keçmək qadağandır", kat: "ustunluk", img: "2-5.gif" },
  { n: "2.6", ad: "Qarşıdan hərəkətin üstünlüyü", kat: "ustunluk", img: "2-6.gif" },
  { n: "2.7", ad: "Qarşıdan hərəkətə nisbətən üstünlük", kat: "ustunluk", img: "2-7.gif" },
  { n: "3.1", ad: "Giriş qadağandır", kat: "qadagan", img: "3.gif" },
  { n: "3.2", ad: "Hərəkət qadağandır", kat: "qadagan", img: "3-2.gif" },
  { n: "3.3", ad: "Mexaniki nəqliyyat vasitələrinin hərəkəti qadağandır", kat: "qadagan", img: "3-3.gif" },
  { n: "3.4", ad: "Yük avtomobillərinin hərəkəti qadağandır", kat: "qadagan", img: "3-4.gif" },
  { n: "3.5", ad: "Motosikletlərin hərəkəti qadağandır", kat: "qadagan", img: "3-5.gif" },
  { n: "3.6", ad: "Traktorların hərəkəti qadağandır", kat: "qadagan", img: "3-6.gif" },
  { n: "3.7", ad: "Qoşqu ilə hərəkət qadağandır", kat: "qadagan", img: "3-7.gif" },
  { n: "3.8", ad: "At-araba ilə hərəkət qadağandır", kat: "qadagan", img: "3-8.gif" },
  { n: "3.9", ad: "Velosipedlə hərəkət qadağandır", kat: "qadagan", img: "3-9.gif" },
  { n: "3.10", ad: "Piyadaların hərəkəti qadağandır", kat: "qadagan", img: "3-10.gif" },
  { n: "3.11", ad: "Kütlənin məhdudlaşdırılması", kat: "qadagan", img: "3-11.gif" },
  { n: "3.12", ad: "Oxa düşən ağırlığın məhdudlaşdırılması", kat: "qadagan", img: "3-12.gif" },
  { n: "3.13", ad: "Hündürlüyün məhdudlaşdırılması", kat: "qadagan", img: "3-13.gif" },
  { n: "3.14", ad: "Enin məhdudlaşdırılması", kat: "qadagan", img: "3-14.gif" },
  { n: "3.15", ad: "Uzunluğun məhdudlaşdırılması", kat: "qadagan", img: "3-15.gif" },
  { n: "3.16", ad: "Minimum ara məsafənin məhdudlaşdırılması", kat: "qadagan", img: "3-16.gif" },
  { n: "3.17.1", ad: "Gömrükxana", kat: "qadagan", img: "3-17.gif" },
  { n: "3.17.2", ad: "Təhlükə", kat: "qadagan", img: "3-17-2.gif" },
  { n: "3.18.1", ad: "Sağa dönmək qadağandır", kat: "qadagan", img: "3-18.gif" },
  { n: "3.18.2", ad: "Sola dönmək qadağandır", kat: "qadagan", img: "3-18-2.gif" },
  { n: "3.19", ad: "Geriyə dönmək qadağandır", kat: "qadagan", img: "3-19.gif" },
  { n: "3.20", ad: "Ötmək qadağandır", kat: "qadagan", img: "3-20.gif" },
  { n: "3.21", ad: "Ötməyin qadağan edildiyi zonanın qurtaracağı", kat: "qadagan", img: "3-21.gif" },
  { n: "3.22", ad: "Yük avtomobillərinin ötməsi qadağandır", kat: "qadagan", img: "3-22.gif" },
  { n: "3.23", ad: "Yük avtomobillərinin ötməsi qadağan edilmiş zonanın qurtaracağı", kat: "qadagan", img: "3-23.gif" },
  { n: "3.24", ad: "Maksimum sürətin məhdudlaşdırılması", kat: "qadagan", img: "3-24.gif" },
  { n: "3.25", ad: "Maksimum sürətin məhdudlaşdırıldığı zonanın qurtaracağı", kat: "qadagan", img: "3-25.gif" },
  { n: "3.26", ad: "Səs siqnalı vermək qadağandır", kat: "qadagan", img: "3-26.gif" },
  { n: "3.27", ad: "Dayanmaq qadağandır", kat: "qadagan", img: "3-27.gif" },
  { n: "3.28", ad: "Durmaq qadağandır", kat: "qadagan", img: "3-28.gif" },
  { n: "3.29", ad: "Ayın tək günlərində durmaq qadağandır", kat: "qadagan", img: "3-29.gif" },
  { n: "3.30", ad: "Ayın cüt günlərində durmaq qadağandır", kat: "qadagan", img: "3-30.gif" },
  { n: "3.31", ad: "Bütün məhdudiyyətlər zonasının qurtaracağı", kat: "qadagan", img: "3-31.gif" },
  { n: "3.32", ad: "Ehtiyat üçün ayrılmış duracaq yeri", kat: "qadagan", img: "3-32.gif" },
  { n: "3.33", ad: "Nəqliyyat vasitələrinin kateqoriyalarına uyğun sürətin məhdudlaşdırılması", kat: "qadagan", img: "3-33.gif" },
  { n: "3.34", ad: "Təhlükəli yükü olan nəqliyyat vasitələrinin hərəkəti qadağandır", kat: "qadagan", img: "3-34.gif" },
  { n: "3.35", ad: "Partlayıcı və tezalışan yükü olan nəqliyyat vasitələrinin hərəkəti qadağandır", kat: "qadagan", img: "3-35.gif" },
  { n: "4.1.1", ad: "Düzünə hərəkət", kat: "mecburi", img: "4-1-1.gif" },
  { n: "4.1.2", ad: "Sağa hərəkət", kat: "mecburi", img: "4-1-2.gif" },
  { n: "4.1.3", ad: "Sola hərəkət", kat: "mecburi", img: "4-1-3.gif" },
  { n: "4.1.4", ad: "Düzünə və ya sağa hərəkət", kat: "mecburi", img: "4-1-4.gif" },
  { n: "4.1.5", ad: "Düzünə və ya sola hərəkət", kat: "mecburi", img: "4-1-5.gif" },
  { n: "4.1.6", ad: "Sağa və ya sola hərəkət", kat: "mecburi", img: "4-1-6.gif" },
  { n: "4.2.1", ad: "Maneəni sağdan keçmə", kat: "mecburi", img: "4-2-1.gif" },
  { n: "4.2.2", ad: "Maneəni soldan keçmə", kat: "mecburi", img: "4-2-2.gif" },
  { n: "4.2.3", ad: "Maneəni sağdan və ya soldan keçmə", kat: "mecburi", img: "4-2-3.gif" },
  { n: "4.3", ad: "Dairəvi hərəkət", kat: "mecburi", img: "4-3.gif" },
  { n: "4.4", ad: "Minik avtomobillərinin hərəkəti", kat: "mecburi", img: "4-4.gif" },
  { n: "4.5", ad: "Velosiped zolağı", kat: "mecburi", img: "4-5.gif" },
  { n: "4.6", ad: "Piyada zolağı", kat: "mecburi", img: "4-6.gif" },
  { n: "4.7", ad: "Minimum sürətin məhdudlaşdırılması", kat: "mecburi", img: "4-7.gif" },
  { n: "4.8", ad: "Minimum sürətin məhdudlaşdırıldığı zonanın qurtaracağı", kat: "mecburi", img: "4-8.gif" },
  { n: "4.9.1", ad: "Təhlükəli yükü olan nəqliyyat vasitələrinin hərəkət istiqaməti", kat: "mecburi", img: "4-9-1.gif" },
  { n: "4.9.2", ad: "Təhlükəli yükü olan nəqliyyat vasitələrinin hərəkət istiqaməti", kat: "mecburi", img: "4-9-2.gif" },
  { n: "4.9.3", ad: "Təhlükəli yükü olan nəqliyyat vasitələrinin hərəkət istiqaməti", kat: "mecburi", img: "4-9-3.gif" },
  { n: "5.1", ad: "Avtomagistral", kat: "melumatverici", img: "5-1.gif" },
  { n: "5.2", ad: "Avtomagistralın qurtaracağı", kat: "melumatverici", img: "5-2.gif" },
  { n: "5.3", ad: "Avtomobillər üçün yol", kat: "melumatverici", img: "5-3.gif" },
  { n: "5.4", ad: "Avtomobillər üçün yolun qurtaracağı", kat: "melumatverici", img: "5-4.gif" },
  { n: "5.5", ad: "Birtərəfli yol", kat: "melumatverici", img: "5-5.gif" },
  { n: "5.6", ad: "Birtərəfli yolun qurtaracağı", kat: "melumatverici", img: "5-6.gif" },
  { n: "5.7.1", ad: "Birtərəfli hərəkət yoluna çıxış", kat: "melumatverici", img: "5-7-1.gif" },
  { n: "5.7.2", ad: "Birtərəfli hərəkət yoluna çıxış", kat: "melumatverici", img: "5-7-2.gif" },
  { n: "5.8.1", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-1.gif" },
  { n: "5.8.2", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-2.gif" },
  { n: "5.8.2", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-2-1.gif" },
  { n: "5.8.2", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-2-3.gif" },
  { n: "5.8.2", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-2-4.gif" },
  { n: "5.8.3", ad: "Zolağın başlanğıcı", kat: "melumatverici", img: "5-8-3.gif" },
  { n: "5.8.3", ad: "Zolağın başlanğıcı", kat: "melumatverici", img: "5-8-3-2.gif" },
  { n: "5.8.4", ad: "Zolağın başlanğıcı", kat: "melumatverici", img: "5-8-4.gif" },
  { n: "5.8.5", ad: "Zolağın qurtaracağı", kat: "melumatverici", img: "5-8-5.gif" },
  { n: "5.8.6", ad: "Zolağın qurtaracağı", kat: "melumatverici", img: "5-8-6.gif" },
  { n: "5.8.7", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-7-1.gif" },
  { n: "5.8.7", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-7-2.gif" },
  { n: "5.8.8", ad: "Zolaqlarda hərəkət istiqamətləri", kat: "melumatverici", img: "5-8-8.gif" },
  { n: "5.9", ad: "Marşrut nəqliyyat vasitələri üçün zolaq", kat: "melumatverici", img: "5-9.gif" },
  { n: "5.10.1", ad: "Marşrut nəqliyyat vasitələri üçün zolağı olan yol", kat: "melumatverici", img: "5-10-1.gif" },
  { n: "5.10.2", ad: "Marşrut nəqliyyat vasitələri üçün zolağı olan yola çıxış", kat: "melumatverici", img: "5-10-2.gif" },
  { n: "5.10.3", ad: "Marşrut nəqliyyat vasitələri üçün zolağı olan yola çıxış", kat: "melumatverici", img: "5-10-3.gif" },
  { n: "5.10.4", ad: "Marşrut nəqliyyat vasitələri üçün zolağı olan yolun qurtaracağı", kat: "melumatverici", img: "5-10-4.gif" },
  { n: "5.11.1", ad: "Geriyə dönmə yeri", kat: "melumatverici", img: "5-11-1.gif" },
  { n: "5.11.2", ad: "Geriyə dönmə yerinin zonası", kat: "melumatverici", img: "5-11-2.gif" },
  { n: "5.12", ad: "Avtobusun və ya trolleybusun dayanacaq yeri", kat: "melumatverici", img: "5-12.gif" },
  { n: "5.13", ad: "Tramvayın dayanacaq yeri", kat: "melumatverici", img: "5-13.gif" },
  { n: "5.14", ad: "Minik taksilərinin dayanacaq yeri", kat: "melumatverici", img: "5-14.gif" },
  { n: "5.15", ad: "Duracaq yeri", kat: "melumatverici", img: "5-15.gif" },
  { n: "5.16.1", ad: "Piyada keçidi", kat: "melumatverici", img: "5-16-1.gif" },
  { n: "5.16.2", ad: "Piyada keçidi", kat: "melumatverici", img: "5-16-2.gif" },
  { n: "5.17.1", ad: "Yeraltı piyada keçidi", kat: "melumatverici", img: "5-17-1.gif" },
  { n: "5.17.2", ad: "Yeraltı piyada keçidi", kat: "melumatverici", img: "5-17-2.gif" },
  { n: "5.17.3", ad: "Yerüstü piyada keçidi", kat: "melumatverici", img: "5-17-3.gif" },
  { n: "5.17.4", ad: "Yerüstü piyada keçidi", kat: "melumatverici", img: "5-17-4.gif" },
  { n: "5.18", ad: "Tövsiyə edilən sürət", kat: "melumatverici", img: "5-18.gif" },
  { n: "5.19.1", ad: "Dalan", kat: "melumatverici", img: "5-19-1.gif" },
  { n: "5.19.2", ad: "Dalan", kat: "melumatverici", img: "5-19-2.gif" },
  { n: "5.19.3", ad: "Dalan", kat: "melumatverici", img: "5-19-3.gif" },
  { n: "5.20.1", ad: "İstiqamətlərin ilkin göstəricisi", kat: "melumatverici", img: "5-20-1.gif" },
  { n: "5.20.1", ad: "İstiqamətlərin ilkin göstəricisi", kat: "melumatverici", img: "5-20-1-1.gif" },
  { n: "5.20.1", ad: "İstiqamətlərin ilkin göstəricisi", kat: "melumatverici", img: "5-20-1-2.gif" },
  { n: "5.20.1", ad: "İstiqamətlərin ilkin göstəricisi", kat: "melumatverici", img: "5-20-1-3.gif" },
  { n: "5.20.2", ad: "İstiqamətin ilkin göstəricisi", kat: "melumatverici", img: "5-20-2.gif" },
  { n: "5.20.3", ad: "Hərəkət sxemi", kat: "melumatverici", img: "5-20-3.gif" },
  { n: "5.21.1", ad: "İstiqamət göstəricisi", kat: "melumatverici", img: "5-21-1.gif" },
  { n: "5.21.2", ad: "İstiqamət göstəricisi", kat: "melumatverici", img: "5-21-2.gif" },
  { n: "5.22", ad: "Yaşayış məntəqəsinin başlanğıcı", kat: "melumatverici", img: "5-22.gif" },
  { n: "5.23", ad: "Yaşayış məntəqəsinin qurtaracağı", kat: "melumatverici", img: "5-23.gif" },
  { n: "5.24", ad: "Yaşayış məntəqəsinin başlanğıcı", kat: "melumatverici", img: "5-24.gif" },
  { n: "5.25", ad: "Yaşayış məntəqəsinin qurtaracağı", kat: "melumatverici", img: "5-25.gif" },
  { n: "5.26", ad: "Obyektin adı", kat: "melumatverici", img: "5-26-1.gif" },
  { n: "5.26", ad: "Obyektin adı", kat: "melumatverici", img: "5-26-2.gif" },
  { n: "5.27", ad: "Məsafələr göstəricisi", kat: "melumatverici", img: "5-27.gif" },
  { n: "5.28", ad: "Killometr göstəricisi", kat: "melumatverici", img: "5-28.gif" },
  { n: "5.29.1", ad: "Marşrut nömrəsi", kat: "melumatverici", img: "5-29-01-1.gif" },
  { n: "5.29.1", ad: "Marşrut nömrəsi", kat: "melumatverici", img: "5-29-1-2.gif" },
  { n: "5.29.2", ad: "Marşrut nömrəsi və istiqaməti", kat: "melumatverici", img: "5-29-02.gif" },
  { n: "5.29.2", ad: "Marşrut nömrəsi və istiqaməti", kat: "melumatverici", img: "5-29-02-2.gif" },
  { n: "5.29.2", ad: "Marşrut nömrəsi və istiqaməti", kat: "melumatverici", img: "5-29-02-3.gif" },
  { n: "5.30.1", ad: "Yük avtomobilləri üçün hərəkət istiqaməti", kat: "melumatverici", img: "5-30-1.gif" },
  { n: "5.30.2", ad: "Yük avtomobilləri üçün hərəkət istiqaməti", kat: "melumatverici", img: "5-30-2.gif" },
  { n: "5.30.3", ad: "Yük avtomobilləri üçün hərəkət istiqaməti", kat: "melumatverici", img: "5-30-3.gif" },
  { n: "5.31", ad: "Kənardankeçmə sxemi", kat: "melumatverici", img: "5-31.gif" },
  { n: "5.32.1", ad: "Kənardankeçmə sxemi", kat: "melumatverici", img: "5-32-2.gif" },
  { n: "5.32.2", ad: "Kənardankeçmə sxemi", kat: "melumatverici", img: "5-32-1.gif" },
  { n: "5.32.3", ad: "Kənardankeçmə sxemi", kat: "melumatverici", img: "5-32-3.gif" },
  { n: "5.33", ad: "Stop-xətt", kat: "melumatverici", img: "5-33.gif" },
  { n: "5.34.1", ad: "Başqa işlək hissəyə yerdəyişmənin ilkin göstəricisi", kat: "melumatverici", img: "5-34-1.gif" },
  { n: "5.34.2", ad: "Başqa işlək hissəyə yerdəyişmənin ilkin göstəricisi", kat: "melumatverici", img: "5-34-2.gif" },
  { n: "5.35", ad: "Qarşılıqlı hərəkət", kat: "melumatverici", img: "5-35.gif" },
  { n: "5.36", ad: "Qarşılıqlı hərəkətin qurtaracağı", kat: "melumatverici", img: "5-36.gif" },
  { n: "5.37", ad: "Qarşılıqlı hərəkət yoluna çıxış", kat: "melumatverici", img: "5-37.gif" },
  { n: "5.38", ad: "Küçənin istiqaməti", kat: "melumatverici", img: "5-38.gif" },
  { n: "5.39", ad: "Kəsişmə yoluna xəbərdaredici və ya qadağanedici nişanlar", kat: "melumatverici", img: "5-39.gif" },
  { n: "6.1", ad: "İlk tibbi yardım məntəqəsi", kat: "servis", img: "6-1.gif" },
  { n: "6.2", ad: "Xəstəxana", kat: "servis", img: "6-2.gif" },
  { n: "6.3", ad: "Yanacaqdoldurma məntəqəsi", kat: "servis", img: "6-3.gif" },
  { n: "6.4", ad: "Avtomobillərə texniki xidmət", kat: "servis", img: "6-4.gif" },
  { n: "6.5", ad: "Avtomobillərin yuyulma məntəqəsi", kat: "servis", img: "6-5.gif" },
  { n: "6.6", ad: "Telefon", kat: "servis", img: "6-6.gif" },
  { n: "6.7", ad: "Yeməkxana", kat: "servis", img: "6-7.gif" },
  { n: "6.8", ad: "İçməli su", kat: "servis", img: "6-8.gif" },
  { n: "6.9", ad: "Mehmanxana və ya motel", kat: "servis", img: "6-9.gif" },
  { n: "6.10", ad: "Kempinq", kat: "servis", img: "6-10.gif" },
  { n: "6.11", ad: "Dincəlmə yeri", kat: "servis", img: "6-11.gif" },
  { n: "6.12", ad: "Yol polisinin daimi məntəqəsi", kat: "servis", img: "6-12.gif" },
  { n: "6.13", ad: "Polis hissəsi", kat: "servis", img: "6-13.gif" },
  { n: "6.14", ad: "İnformasiya stendi", kat: "servis", img: "6-14.gif" },
  { n: "6.15", ad: "Tualet", kat: "servis", img: "6-15.gif" },
  { n: "6.16", ad: "Çimərlik", kat: "servis", img: "6-16.gif" },
  { n: "7.1.1", ad: "Obyektə qədər məsafə", kat: "elave-melumat", img: "7-1-1.gif" },
  { n: "7.1.2", ad: "Obyektə qədər məsafə", kat: "elave-melumat", img: "7-1-2.gif" },
  { n: "7.1.3", ad: "Obyektə qədər məsafə", kat: "elave-melumat", img: "7-1-3.gif" },
  { n: "7.1.4", ad: "Obyektə qədər məsafə", kat: "elave-melumat", img: "7-1-4.gif" },
  { n: "7.2.1", ad: "Qüvvədə olma zonası", kat: "elave-melumat", img: "7-2-1.gif" },
  { n: "7.2.2", ad: "Qüvvədə olma zonası", kat: "elave-melumat", img: "7-2-2.gif" },
  { n: "7.2.3", ad: "Qüvvədə olma zonası", kat: "elave-melumat", img: "7-2-3.gif" },
  { n: "7.2.4", ad: "Qüvvədə olma zonası", kat: "elave-melumat", img: "7-2-4.gif" },
  { n: "7.2.5", ad: "Qüvvədə olma zonası", kat: "elave-melumat", img: "7-2-5.gif" },
  { n: "7.2.6", ad: "Qüvvədə olma zonası", kat: "elave-melumat", img: "7-2-6.gif" },
  { n: "7.2.7", ad: "Qüvvədə olma zonası", kat: "elave-melumat", img: "7-2-7.gif" },
  { n: "7.3.1", ad: "Qüvvədə olma istiqaməti", kat: "elave-melumat", img: "7-3-1.gif" },
  { n: "7.3.2", ad: "Qüvvədə olma istiqaməti", kat: "elave-melumat", img: "7-3-2.gif" },
  { n: "7.3.3", ad: "Qüvvədə olma istiqaməti", kat: "elave-melumat", img: "7-3-3.gif" },
  { n: "7.4.1", ad: "Nəqliyyat vasitəsinin növü", kat: "elave-melumat", img: "7-4-1.gif" },
  { n: "7.4.2", ad: "Nəqliyyat vasitəsinin növü", kat: "elave-melumat", img: "7-4-2.gif" },
  { n: "7.4.3", ad: "Nəqliyyat vasitəsinin növü", kat: "elave-melumat", img: "7-4-3.gif" },
  { n: "7.4.4", ad: "Nəqliyyat vasitəsinin növü", kat: "elave-melumat", img: "7-4-4.gif" },
  { n: "7.4.5", ad: "Nəqliyyat vasitəsinin növü", kat: "elave-melumat", img: "7-4-5.gif" },
  { n: "7.4.6", ad: "Nəqliyyat vasitəsinin növü", kat: "elave-melumat", img: "7-4-6.gif" },
  { n: "7.4.7", ad: "Nəqliyyat vasitəsinin növü", kat: "elave-melumat", img: "7-4-7.gif" },
  { n: "7.5.1", ad: "Şənbə, bazar və bayram günləri", kat: "elave-melumat", img: "7-5-1.gif" },
  { n: "7.5.2", ad: "İş günləri", kat: "elave-melumat", img: "7-5-2.gif" },
  { n: "7.5.3", ad: "Həftənin günləri", kat: "elave-melumat", img: "7-5-3.gif" },
  { n: "7.5.4", ad: "Qüvvədə olma vaxtı", kat: "elave-melumat", img: "7-5-4.gif" },
  { n: "7.5.5", ad: "Qüvvədə olma vaxtı", kat: "elave-melumat", img: "7-5-5.gif" },
  { n: "7.5.6", ad: "Qüvvədə olma vaxtı", kat: "elave-melumat", img: "7-5-6.gif" },
  { n: "7.5.7", ad: "Qüvvədə olma vaxtı", kat: "elave-melumat", img: "7-5-7.gif" },
  { n: "7.6.1", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-1.gif" },
  { n: "7.6.2", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-2.gif" },
  { n: "7.6.3", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-3.gif" },
  { n: "7.6.4", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-4.gif" },
  { n: "7.6.5", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-5.gif" },
  { n: "7.6.6", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-6.gif" },
  { n: "7.6.7", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "1-7-6-6.gif" },
  { n: "7.6.8", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-8.gif" },
  { n: "7.6.9", ad: "Nəqliyyat vasitələrinin duracağa qoyulma üsulu", kat: "elave-melumat", img: "7-6-9.gif" },
  { n: "7.7", ad: "İşləməyən mühərriklə durma", kat: "elave-melumat", img: "7-7.gif" },
  { n: "7.8", ad: "Pullu xidmətlər", kat: "elave-melumat", img: "7-8.gif" },
  { n: "7.9", ad: "Durma müddətinin məhdudlaşdırılması", kat: "elave-melumat", img: "7-9.gif" },
  { n: "7.10", ad: "Avtomobillərə baxış üçün yer", kat: "elave-melumat", img: "7-10.gif" },
  { n: "7.11", ad: "İcazə verilən kütlənin məhdudlaşdırılması", kat: "elave-melumat", img: "7-11.gif" },
  { n: "7.12", ad: "Təhlükəli yol qırağı", kat: "elave-melumat", img: "7-12.gif" },
  { n: "7.13", ad: "Baş yolun istiqaməti", kat: "elave-melumat", img: "7-13.gif" },
  { n: "7.14", ad: "Hərəkət zolağı", kat: "elave-melumat", img: "7-14.gif" },
  { n: "7.15", ad: "Kor piyadalar", kat: "elave-melumat", img: "7-15.gif" },
  { n: "7.16", ad: "Yaş örtük", kat: "elave-melumat", img: "7-16.gif" },
  { n: "7.17", ad: "Əlillər", kat: "elave-melumat", img: "7-17.gif" },
  { n: "7.18", ad: "Əlillərdən başqa", kat: "elave-melumat", img: "7-18.gif" },
  { n: "7.19", ad: "Faranın yaxın işığı ilə hərəkət", kat: "elave-melumat", img: "7-19.gif" },
  { n: "", ad: "Avtomobil qatarının tanınma nişanı", kat: "taninma", img: "1-1.gif" },
  { n: "", ad: "Avtomobil qatarının tanınma nişanı", kat: "taninma", img: "1-1-2.gif" },
  { n: "", ad: "Tikanlı şinləri olan nəqliyyat vasitəsinin tanınma nişanı", kat: "taninma", img: "tikanli.gif" },
  { n: "", ad: "Qrupla uşaq aparan nəqliyyat vasitəsinin tanınma nişanı", kat: "taninma", img: "qrupla-ushaq.gif" },
  { n: "", ad: "Uzunluğu 24 m-dən artıq olan nəqliyyat vasitələri tərkibinin tanınma nişanı", kat: "taninma", img: "uzunlugu.gif" },
  { n: "", ad: "Qəza dayanacağı nişanı", kat: "taninma", img: "qeza2.gif" },
  { n: "", ad: "Azərbaycan Respublikası nəqliyyat vasitələrinin beynəlxalq yol hərəkətlərində fərqlənmə nişanı", kat: "taninma", img: "azerbaycan.gif" },
  { n: "", ad: "Təcrübəsiz sürücü", kat: "taninma", img: "tecrubesiz.gif" },
  { n: "", ad: "Kar və ya lal-kar sürücü tərəfindən idarə edilən avtomobilin tanınma nişanı", kat: "taninma", img: "kar-lal.gif" },
  { n: "", ad: "Əlil tərəfindən idarə edilən avtomobilin tanınma nişanı", kat: "taninma", img: "elil.gif" },
  { n: "", ad: "Sürücü-həkim tərəfindən idarə edilən avtomobilin tanınma nişanı", kat: "taninma", img: "surucu.gif" },
  { n: "", ad: "Təlim-nəqliyyat vasitəsi nişanı", kat: "taninma", img: "t.gif" },
  { n: "", ad: "Nəqliyyat vasitəsinin qabaritindən kənara çıxan yükün tanınma nişanı", kat: "taninma", img: "neql.gif" },
  { n: "", ad: "Təhlükəli yük aparan avtomobilin tanınma nişanı", kat: "taninma", img: "tehlukeli-yuk.png" },
  { n: "1", ad: "Görülməli işlərin sahəsini müəyyənləşdirən lövhə və səyyari konuslar", kat: "yol-isleri", img: "1-1.gif" },
  { n: "1", ad: "Görülməli işlərin sahəsini müəyyənləşdirən lövhə və səyyari konuslar", kat: "yol-isleri", img: "1-2.gif" },
  { n: "2", ad: "Nizamlayıcı göstərişləri olan hərəkət lövhələri", kat: "yol-isleri", img: "2-1.gif" },
  { n: "2", ad: "Nizamlayıcı göstərişləri olan hərəkət lövhələri", kat: "yol-isleri", img: "2-2.gif" },
  { n: "2", ad: "Nizamlayıcı göstərişləri olan hərəkət lövhələri", kat: "yol-isleri", img: "2-3.gif" },
  { n: "3", ad: "İş sahəsini müəyyənləşdirən qırmızı və ya narıncı rəngli sayrışan işıqlar", kat: "yol-isleri", img: "1-3.gif" },
  { n: "4", ad: "Hərəkətin istiqamətini göstərən maneə", kat: "yol-isleri", img: "4.gif" },
  { n: "5", ad: "Görülən yol işlərindən yan keçməni göstərən maneələr", kat: "yol-isleri", img: "5.gif" },
  { n: "6", ad: "Yol işləri sahəsinin müəyyən edilməsi üçün bayraqlar", kat: "yol-isleri", img: "6.gif" },
  { n: "1.1", ad: "əks istiqamətli nəqliyyat axınlarını ayırır və yolların təhlükəli yerlərində hərəkət zolaqlarının sərhədini, yolun hərəkət hissəsinin giriş qadağan edilən sərhədlərini, nəqliyyat vasitələrinin duracaq yerlərinin sərhədlərini və avtomagistrallara aid edilməyən yolların hərəkət hissəsinin kənarlarını göstərir", kat: "nisanlanma", img: "1.jpg" },
  { n: "1.2", ad: "avtomagistrallarda hərəkət hissəsinin kənarını göstərir (enli bütöv xətlər)", kat: "nisanlanma", img: "2.jpg" },
  { n: "1.3", ad: "dörd və daha çox hərəkət zolağı olan yollarda əks istiqamətli nəqliyyat axınlarını ayırır;", kat: "nisanlanma", img: "3.jpg" },
  { n: "1.4", ad: "dayanma qadağan olunan yerləri bildirir, müstəqil və ya 3.27 nişanı ilə birlikdə tətbiq edilir və hərəkət hissəsinin kənarına və ya bordürün üst hissəsində çəkilir;", kat: "nisanlanma", img: "4.jpg" },
  { n: "1.5", ad: "iki və ya üç zolağı olan yollarda əks istiqamətli nəqliyyat axınlarını ayırır, bir istiqamətdə hərəkət üçün iki və daha çox zolaq olduqda, hərəkət zolaqlarının sərhədlərini göstərir;", kat: "nisanlanma", img: "5.jpg" },
  { n: "1.6", ad: "əks istiqamətli və ya eyni istiqamətli nəqliyyat axınlarını ayıran 1.1 və ya 1.11 nişanlanma xətlərinə yaxınlaşma barədə xəbərdarlıq edir (yaxınlaşma xətti - cizgilərinin uzunluğu onların aralarındakı məsafədən üç dəfə böyük olan qırıq xətlər);", kat: "nisanlanma", img: "6.jpg" },
  { n: "1.7", ad: "yolayrıcının hüdudlarında hərəkət zolaqlarını göstərir (cizgiləri qısa və onların aralarındakı məsafə cizginin uzunluğuna bərabər olan qırıq xətlər);", kat: "nisanlanma", img: "7.jpg" },
  { n: "1.8", ad: "sürətləndirmə və ya tormozlama zolağı ilə yolun hərəkət hissəsinin əsas zolağı arasında sərhədi göstərir (enli qırıq xətlər müxtəlif səviyyələrdəki yolayrıclarında, kəsişmələrdə, avtobus dayanacaqları zonasında və sair yerlərdə);", kat: "nisanlanma", img: "8.jpg" },
  { n: "1.9", ad: "reversiv hərəkətlə nizamlanma tətbiq edilən hərəkət zolaqlarının sərhədlərini göstərir, qarşılıqlı hərəkətlə nizamlanma tətbiq olunan yollarda əks istiqamətli (qarşılıqlı hərəkət svetoforları söndürülən zaman) nəqliyyat axınlarını ayırır;", kat: "nisanlanma", img: "9.jpg" },
  { n: "1.10", ad: "duracağın qadağan olunduğu yerləri bildirir, müstəqil və ya 3.28 nişanı ilə birlikdə tətbiq olunur və hərəkət hissəsinin kənarına və ya bordürün üst hissəsində çəkilir;", kat: "nisanlanma", img: "10.jpg" },
  { n: "1.11", ad: "yalnız bir zolaqdan çıxaraq yerdəyişməyə icazə verilən yol sahələrində əks və ya eyni istiqamətli nəqliyyat axınlarını ayırır və yalnız bir tərəfə hərəkət etməyə icazə verilən yollarda duracaqlara girmək və çıxmaq, geriyə dönmək və sair üçün nəzərdə tutulmuş yerləri göstərir;", kat: "nisanlanma", img: "11.jpg" },
  { n: "1.12", ad: "(stop-xətt) - 2.5 nişanı olduqda və ya svetoforun (nizamlayıcının) qadağan siqnalı verildikdə, sürücünün dayanmalı olduğu yeri göstərir;", kat: "nisanlanma", img: "12.jpg" },
  { n: "1.13", ad: "kəsişən yolla hərəkət edən nəqliyyat vasitələrinə yol vermək üçün sürücünün lazım gəldikdə, dayanmalı olduğu yeri göstərir;", kat: "nisanlanma", img: "13.jpg" },
  { n: "1.14.1", ad: "nizamlanmayan piyada keçidini,", kat: "nisanlanma", img: "14.jpg" },
  { n: "1.14.2", ad: "piyadaların hərəkət istiqamətini,", kat: "nisanlanma", img: "15.jpg" },
  { n: "1.14.3", ad: "hərəkətin svetoforla nizamlandığı piyada keçidini göstərir;", kat: "nisanlanma", img: "16.jpg" },
  { n: "1.15", ad: "velosiped yolunun yolun hərəkət hissəsi ilə kəsişdiyi yeri göstərir;", kat: "nisanlanma", img: "17.jpg" },
  { n: "1.16.1", ad: "1.16.3 - nəqliyyat axınlarının ayrıldığı və ya birləşdiyi yerlərdə istiqamətləndirici adacıqları göstərir; 1.16.1 əks istiqamətli nəqliyyat axınlarını ayırır;", kat: "nisanlanma", img: "18.jpg" },
  { n: "1.16.2", ad: "eyni istiqamətli nəqliyyat axınlarını ayırır;", kat: "nisanlanma", img: "19.jpg" },
  { n: "1.16.3", ad: "eyni istiqamətli nəqliyyat axınlarını birləşdirir;", kat: "nisanlanma", img: "2-20.jpg" },
  { n: "1.17", ad: "ümumi istifadədə olan nəqliyyat vasitələrinin dayanacaqlarını və taksi duracaqlarını göstərir;", kat: "nisanlanma", img: "3-21.jpg" },
  { n: "1.18", ad: "yolayrıcında hərəkətin zolaqlar üzrə icazə verilmiş istiqamətlərini göstərir, müstəqil, yaxud 5.8.1, 5.8.2 nişanları ilə birlikdə tətbiq edilir, dalan təsviri çəkilmiş nişanlama xətti göstərir ki, yaxınlıqdakı hərəkət hissəsinə dönmək qadağandır, sol kənar zolaqdan sola dönməyə icazə verən işarə həmin zolaqdan geriyə dönməyə də icazə verir;", kat: "nisanlanma", img: "20-5.jpg" },
  { n: "1.19", ad: "yolun hərəkət hissəsinin daralan sahəsinə (həmin istiqamətdə zolaqların sayının azaldığı sahəyə), yaxud əks istiqamətlərdə nəqliyyat axınlarını ayıran 1.1 və 1.11 nişanlama xətlərinə yaxınlaşmanı göstərir. Birinci halda 1.19 nişanlama xətti 1.18.1-1.18.3 nişanları ilə birlikdə tətbiq oluna bilər;", kat: "nisanlanma", img: "1-22.jpg" },
  { n: "1.20", ad: "1.13 nişanlanma xəttinə yaxınlaşmanı bildirir;", kat: "nisanlanma", img: "1-23.jpg" },
  { n: "1.21", ad: "(«stop» yazısı) - 2.5 nişanı ilə birlikdə tətbiq olunduğu hallarda 1.12 nişanlanma xəttinə yaxınlaşmanı bildirir;", kat: "nisanlanma", img: "24.jpg" },
  { n: "1.22", ad: "yolun (marşrutun) nömrəsini göstərir;", kat: "nisanlanma", img: "25.jpg" },
  { n: "1.23", ad: "ümumi istifadədə olan nəqliyyat vasitələri üçün xüsusi zolağı göstərir.", kat: "nisanlanma", img: "26.jpg" },
  { n: "1.24", ad: "əlillərin nəqliyyat vasitələri", kat: "nisanlanma", img: "27.jpg" },
  { n: "2.1", ad: "yol qurğularının hərəkətdə olan nəqliyyat vasitələri üçün təhlükə doğuran ünsürlərini (körpülərin dayaqlarını və s.) göstərir; 2.2 - tunellərin, körpülərin aşırımlarının aşağı kənarını göstərir;", kat: "nisanlanma", img: "1-1-1.jpg" },
  { n: "2.3", ad: "ayırma zolaqlarında və ya təhlükəsizlik adacıqlarında düzəldilmiş dairəvi adacıqları göstərir; 2.4 - istiqamətləndirici dirəkcikləri, yolkənarı kötükcükləri, çəpərlərin dayaqlarını və s. göstərir 2.5 - kiçik radiuslu döngələrdə, sərt enişlərdə, digər təhlükəli sahələrdə yol sədlərinin yan səthini göstərir; 2.6 - başqa sahələrdə yol sədlərinin yan səthini göstərir;", kat: "nisanlanma", img: "1-2.jpg" },
  { n: "2.7", ad: "təhlükəli sahələrdə yol səthindən hündürə çıxan təhlükəsizlik adacıqlarını göstərir.", kat: "nisanlanma", img: "1-3.jpg" },
];
